name: Workflow

on: 
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: macos-latest
    name: check workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install  
      - name : Testing the tests
        run: npm test
